# Generated by Django 6.0.6 on 2026-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethubapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
